name: example
description: An example app for reactive_multi_image_picker
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-0 <3.0.0"
  flutter: ">=2.5.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^11.0.0
  freezed_annotation: ^0.15.0
  reactive_multi_image_picker:
    path: ../
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^0.15.0+1

flutter:
  uses-material-design: true
